#!/usr/bin/env bash
# Status lives only in docs/specs/*/spec.md. This script derives the board.
#   scripts/backlog.sh           regenerate docs/product/backlog.md
#   scripts/backlog.sh --check   fail if backlog.md is stale
#   scripts/backlog.sh --next    Planned/In Progress specs whose deps are all Done
# A dependency with no spec folder is legacy history and counts as Done.
set -euo pipefail
cd "$(dirname "$0")/.."
out=docs/product/backlog.md

rows() { # id|status|title|deps|dir
  for s in docs/specs/LCV-*/spec.md; do
    [[ -e $s ]] || continue
    d=$(dirname "$s")
    id=$(basename "$d" | cut -d- -f1-2)
    title=$(head -1 "$s" | sed -E 's/^# LCV-[0-9]+ *[-—] *//')
    st=$(sed -nE 's/^- \*\*Status\*\*: *(.*)$/\1/p' "$s" | head -1)
    deps=$(sed -nE 's/^- \*\*Depends on\*\*: *(.*)$/\1/p' "$s" | head -1)
    echo "$id|$st|$title|$deps|$d"
  done
}

status_of() { rows | awk -F'|' -v id="$1" '$1==id{print $2}'; }

render() {
  echo "# Backlog"
  echo
  echo "Generated by \`scripts/backlog.sh\` from \`docs/specs/*/spec.md\` — do not edit by hand."
  for st in "In Progress" Planned Specified Draft Blocked Done Rejected; do
    body=$(rows | awk -F'|' -v st="$st" '$2==st{printf "| [%s](../specs/%s/spec.md) | %s | %s |\n",$1,substr($5,12),$3,$4}')
    [[ -z $body ]] && continue
    printf '\n## %s\n\n| ID | Title | Depends on |\n|---|---|---|\n%s\n' "$st" "$body"
  done
}

case "${1:-}" in
  --check)
    if ! diff -q <(render) "$out" >/dev/null; then
      echo "backlog.md is stale: run scripts/backlog.sh"; exit 1; fi ;;
  --next)
    rows | while IFS='|' read -r id st title deps dir; do
      [[ $st == Planned || $st == "In Progress" ]] || continue
      ok=1
      for dep in $(grep -oE 'LCV-[0-9]+' <<<"$deps"); do
        ds=$(status_of "$dep"); [[ -z $ds || $ds == Done ]] || ok=0
      done
      (( ok )) && echo "$id  [$st]  $title  ($dir)"
    done ;;
  "") render > "$out"; echo "wrote $out" ;;
  *) echo "usage: $0 [--check|--next]"; exit 2 ;;
esac
